# Basics of Represent Infomartions
date written: 2024-07-10


### Table of Contents
- How do we represent data using mathematical notations?
- Is there any rules or convention we need to understand?
- What are the library you need to know?

#### Vectors and Matrices in Python

The fact that Qiskit, one of the famous quantum programming tools is using `python` programming language. So we would learn we would learn how to represent mathematical notations on `numPy` 

So according to linear algebra convention:
1. `vector` is used to represent `bit`
2. `matrices` is used to represent `operator`

And the tools we use for it is `array`

In [7]:
from numpy import array 

ket0 = array([1,0])
ket1 = array([0,1])

display(ket0/2 + ket1/2)

array([0.5, 0.5])

and if you came from computer science background, you might familiar with using 2-dimensional array to represent the `matrices`

In [9]:
M1 = array([[1,1], [0,0]])
M2 = array([[1,1], [1,0]])

display(M1/2 + M2/2)

array([[1. , 1. ],
       [0.5, 0. ]])

to multiply matrices, we have `matmul`to solved them simply

In [13]:
from numpy import matmul

display(matmul(M1, ket1))
display(matmul(M1, M2)) # (M1)(M2)
display(matmul(M2, M1)) # (M2)(M1)

array([1, 0])

array([[2, 1],
       [0, 0]])

array([[1, 1],
       [1, 1]])

#### States, measurements, and operations

As we have seen so far, you might thought, but how it is actually represent data, "Are all vectors and matrices valid?"

This is when we will explain the them in full detail:

###### First, we have to understand **Dirac Notation**
- define |x⟩ as a column vector, x ∈ Σ, if Σ = {0, 1} then `|0⟩ = Statevector([1,0])` and `|1⟩ = Statevector([0,1])`
    - Σ is set of all possible basis
    - |x⟩ is basis vectors, while number of entries corresponding to elements of Σ
    - for arbitary states vector from would be `|ψ⟩ = Statevector([alpha, beta])`, think of it as probabilities of happened to be zero or one

###### What is the differences between general sets of vectors and quantum states vectors?
We must understand 3 types of states
1. Some invalid state or unnormalized states 
    - sum of coefficient can be any number
2. **probabilistic states** is a form of *classical states* 
    - coefficient can be only *Real number*
    - coefficient can not be *negative* 
    - sum of coefficient must be 1
3. **quantum states**
    - coeffient can be *Imaginary number* 
    - sum of absoluted coefficient square must be 1

Now what do `Statevector` represent? Answer is **quantum states**

In [1]:
from qiskit.quantum_info import Statevector
from numpy import sqrt

u = Statevector([1/sqrt(2), 1/sqrt(2)])
v = Statevector([(1+2.0j)/3, -2/3])
w = Statevector([1/3, 2/3])

print("State vectors u, v, w is defined as: ")
display(u.draw("latex"))
display(v.draw("latex"))
display(w.draw("latex"))

State vectors u, v, w is defined as: 


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

If parameter that puts into `Statevector` can be any number, how we could which one is valid quantum states

In [4]:
print('u is valid:', u.is_valid())
print('v is valid:', v.is_valid())
print('w is valid:', w.is_valid())

u is valid: True
v is valid: True
w is valid: False
