# Basics of Represent Infomartions
date written: 2024-07-10


### Table of Contents
- How do we represent data using mathematical notations?

#### Vectors and Matrices in Python

The fact that Qiskit, one of the famous quantum programming tools is using `python` programming language. So we would learn we would learn how to represent mathematical notations on `numPy` 

So according to linear algebra convention:
1. `vector` is used to represent `bit`
2. `matrices` is used to represent `operator`

And the tools we use for it is `array`

In [7]:
from numpy import array 

ket0 = array([1,0])
ket1 = array([0,1])

display(ket0/2 + ket1/2)

array([0.5, 0.5])

and if you came from computer science background, you might familiar with using 2-dimensional array to represent the `matrices`

In [9]:
M1 = array([[1,1], [0,0]])
M2 = array([[1,1], [1,0]])

display(M1/2 + M2/2)

array([[1. , 1. ],
       [0.5, 0. ]])

to multiply matrices, we have `matmul`to solved them simply

In [13]:
from numpy import matmul

display(matmul(M1, ket1))
display(matmul(M1, M2)) # (M1)(M2)
display(matmul(M2, M1)) # (M2)(M1)

array([1, 0])

array([[2, 1],
       [0, 0]])

array([[1, 1],
       [1, 1]])

#### States, measurements, and operations

As we have seen so far, you might thought, but how it is actually represent data, "Are all vectors and matrices valid?"

This is when we will explain the them in full detail:

First, we have to understand **Dirac Notation**